version: '2'
services:
  web:
    container_name: 'web'
    # point to Dockerfile to build an image and use it afterwards
    build: .  
    ports:
    # map ports from HOST:CONTAINER
      - "80:80"
    volumes:
    - ./app:/app
    # link to other container postgres and its service
    depends_on:
      - postgres

  postgres:
    container_name: 'postgres'
    image: postgres:latest
    environment:
      # set the same ENV variables specified in config.py
      POSTGRES_USER : foo
      POSTGRES_PASSWORD : foobar
      POSTGRES_DB : prod
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  pgdata: