version: '2'
services:
  web:
    container_name: 'web'
    build: .
    ports: 
      - "80:80"
    volumes:
    - ./app:/app
    depends_on:
      - postgres

  postgres:
    container_name: 'postgres'
    image: postgres:latest
    environment:
      POSTGRES_USER : foo
      POSTGRES_PASSWORD : foobar
      POSTGRES_DB : prod
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  pgdata: